# Generated by Django 3.2.5 on 2021-11-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='帳號')),
                ('password', models.CharField(max_length=16, verbose_name='密碼')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子郵件')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '會員',
                'verbose_name_plural': '會員',
                'ordering': ['c_time'],
            },
        ),
    ]
