# Generated by Django 3.2.5 on 2022-03-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20220326_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='content',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='piccontent',
            field=models.TextField(default='content'),
        ),
        migrations.AddField(
            model_name='photo',
            name='pictitle',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
