# Generated by Django 3.2.5 on 2022-03-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20220326_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='piccontent',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pictitle',
            field=models.TextField(default='', max_length=50),
        ),
    ]
