# Generated by Django 3.2.5 on 2022-03-26 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20220326_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
