# Generated by Django 3.2.5 on 2022-03-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_delete_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='works/', verbose_name='插入圖片'),
        ),
    ]
