# Generated by Django 3.2.5 on 2022-03-28 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
